/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import controle.ConectaBanco;
import controle.ControleBairro;
import modelo.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloBairro;

/**
 *
 * @author heito
 */
public class FrmBairro extends javax.swing.JFrame {

    private boolean estadoVazio;
    ConectaBanco connCidade = new ConectaBanco();
    ConectaBanco connBairro = new ConectaBanco();
    ModeloBairro modBairro = new ModeloBairro();
    ControleBairro control = new ControleBairro();

    /**
     * Creates new form FrmBairro
     */
    public FrmBairro() {
        initComponents();
        this.estadoVazio = false;
        connCidade.conexao();
        connBairro.conexao();
        preecherTabela(" select * from tb_bairro inner join tb_cidade on tb_bairro.id_cidade = tb_cidade.id_cidade");
        connCidade.executaSQL("select * from TB_cidade order by nome_cidade");
        jComboBoxCidade.removeAllItems();
        try {
            connCidade.rs.first();
            do {
                jComboBoxCidade.addItem(connCidade.rs.getString("nome_cidade"));
            } while (connCidade.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você precisa cadastra uma cidade:" + ex);
            this.estadoVazio = true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxCidade = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbuttonAdicionar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jbuttonAlterar = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jTextFieldCod = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de estado");

        jComboBoxCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Códico:");

        jLabel3.setText("Nome:");

        jbuttonAdicionar.setText("Adicionar");
        jbuttonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonAdicionarActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jbuttonAlterar.setText("Alterar");
        jbuttonAlterar.setEnabled(false);
        jbuttonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonAlterarActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.setEnabled(false);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonPrimeiro.setText("Primeiro");
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });

        jButtonUltimo.setText("Ultimo");
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        jButtonProximo.setText("Proximo");
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonAnterior.setText("Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabela);

        jTextFieldCod.setEditable(false);
        jTextFieldCod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCodMouseClicked(evt);
            }
        });
        jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodActionPerformed(evt);
            }
        });

        jTextFieldNome.setEnabled(false);
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbuttonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuttonAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonPrimeiro)
                                .addGap(5, 5, 5)
                                .addComponent(jButtonAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonProximo))
                            .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonUltimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonAdicionar)
                    .addComponent(jbuttonAlterar)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonPrimeiro)
                    .addComponent(jButtonUltimo)
                    .addComponent(jButtonProximo)
                    .addComponent(jButtonSair)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonAnterior))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Formulário de cadastro de bairro");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        setSize(new java.awt.Dimension(823, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        inserirCidade();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jbuttonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonAdicionarActionPerformed
        // TODO add your handling code here:
        jTextFieldNome.setEnabled(true);
        jbuttonAlterar.setEnabled(true);
        jButtonDelete.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jbuttonAdicionar.setEnabled(false);
        jTextFieldNome.setText("");
        jTextFieldCod.setText("");
    }//GEN-LAST:event_jbuttonAdicionarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        FrmCidade frm = new FrmCidade();
        if (frm.getEstadoVazio()) {
            frm.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldNome.setEnabled(false);
        jbuttonAlterar.setEnabled(false);
        jButtonDelete.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jbuttonAdicionar.setEnabled(true);
        jTextFieldNome.setText("");
        jTextFieldCod.setText("");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jbuttonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonAlterarActionPerformed
        // TODO add your handling code here:
        try {

            connCidade.executaSQL("select * from TB_cidade where nome_cidade ='" + jComboBoxCidade.getSelectedItem() + "'");
            connCidade.rs.first();

            modBairro.setCod(Integer.parseInt(jTextFieldCod.getText()));
            modBairro.setNome(jTextFieldNome.getText());
            modBairro.setCodCidade(connCidade.rs.getInt("id_cidade"));
            control.alterarBairro(modBairro);

            preecherTabela(" select * from tb_bairro inner join tb_cidade on tb_bairro.id_cidade = tb_cidade.id_cidade");
            jTextFieldNome.setEnabled(false);
            jbuttonAlterar.setEnabled(false);
            jButtonDelete.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jbuttonAdicionar.setEnabled(true);
            jTextFieldNome.setText("");
            jTextFieldCod.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "erro ao alterar o registro!/n ERRO:" + ex);
        }
    }//GEN-LAST:event_jbuttonAlterarActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int codigo = Integer.parseInt(jTextFieldCod.getText());
            System.out.println(codigo);
            modBairro.setCod(codigo);
            modBairro.setNome(jTextFieldNome.getText());
            modBairro.setCodCidade(connBairro.rs.getInt("id_cidade"));
            control.excluiCidade(modBairro);
            preecherTabela(" select * from tb_bairro inner join tb_cidade on tb_bairro.id_cidade = tb_cidade.id_cidade");
            jTextFieldNome.setEnabled(false);
            jbuttonAlterar.setEnabled(false);
            jButtonDelete.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jbuttonAdicionar.setEnabled(true);
            jTextFieldNome.setText("");
            jTextFieldCod.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "erro ao excluir o registro!/n ERRO:" + ex);
        }

    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        // TODO add your handling code here:jButtonAlterar.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jbuttonAlterar.setEnabled(true);
        jButtonDelete.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jbuttonAdicionar.setEnabled(false);
        jTextFieldNome.setEnabled(true);
        try {
            connBairro.executaSQL("select * from tb_bairro order by id_bairro");
            connBairro.rs.first();
            jTextFieldCod.setText(String.valueOf(connBairro.rs.getInt("id_bairro")));
            jTextFieldNome.setText(connBairro.rs.getString("nome_bairro"));
            connCidade.executaSQL("select * from tb_cidade where id_cidade=" + connBairro.rs.getInt("id_cidade"));
            connCidade.rs.first();
            jComboBoxCidade.setSelectedItem(connCidade.rs.getString("nome_cidade"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "erro ao o primeiro registro!/n ERRO:" + ex);
        }
    }//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        // TODO add your handling code here:
        jButtonSalvar.setEnabled(false);
        jbuttonAlterar.setEnabled(true);
        jButtonDelete.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jbuttonAdicionar.setEnabled(false);
        jTextFieldNome.setEnabled(true);
        try {
            connBairro.executaSQL("select * from tb_bairro order by id_bairro");
            connBairro.rs.last();
            jTextFieldCod.setText(String.valueOf(connBairro.rs.getInt("id_bairro")));
            jTextFieldNome.setText(connBairro.rs.getString("nome_bairro"));
            connCidade.executaSQL("select * from tb_cidade where id_cidade=" + connBairro.rs.getInt("id_cidade"));
            connCidade.rs.first();
            jComboBoxCidade.setSelectedItem(connCidade.rs.getString("nome_cidade"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "erro ao o primeiro registro!/n ERRO:" + ex);
        }
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
        jButtonSalvar.setEnabled(false);
        jbuttonAlterar.setEnabled(true);
        jButtonDelete.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jbuttonAdicionar.setEnabled(false);
        jTextFieldNome.setEnabled(true);
        try {
            //connBairro.executaSQL("select * from tb_bairro order by id_bairro");
            connBairro.rs.next();
            jTextFieldCod.setText(String.valueOf(connBairro.rs.getInt("id_bairro")));
            jTextFieldNome.setText(connBairro.rs.getString("nome_bairro"));
            connCidade.executaSQL("select * from tb_cidade where id_cidade=" + connBairro.rs.getInt("id_cidade"));
            connCidade.rs.first();
            jComboBoxCidade.setSelectedItem(connCidade.rs.getString("nome_cidade"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "erro ao o primeiro registro!/n ERRO:" + ex);
        }
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:
        jbuttonAlterar.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jButtonDelete.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jbuttonAdicionar.setEnabled(false);
        jTextFieldNome.setEnabled(true);
        try {
            // connBairro.executaSQL("select * from tb_bairro order by id_bairro");
            connBairro.rs.previous();
            jTextFieldCod.setText(String.valueOf(connBairro.rs.getInt("id_bairro")));
            jTextFieldNome.setText(connBairro.rs.getString("nome_bairro"));
            connCidade.executaSQL("select * from tb_cidade where id_cidade=" + connBairro.rs.getInt("id_cidade"));
            connCidade.rs.first();
            jComboBoxCidade.setSelectedItem(connCidade.rs.getString("nome_cidade"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "erro ao o primeiro registro!/n ERRO:" + ex);
        }
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jTextFieldCodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCodMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodMouseClicked

    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed
    public void preecherTabela(String SQL) {
        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"id", "TB_bairro", "cidade"};

        connBairro.executaSQL(SQL);
        try {
            connBairro.rs.first();
            do {

                var obj = new Object[]{
                    connBairro.rs.getInt("id_bairro"),
                    connBairro.rs.getString("nome_bairro"),
                    connBairro.rs.getString("nome_cidade")
                };
                dados.add(obj);
            } while (connBairro.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preecher o ArrayList!\nERRO:" + ex);
        }

        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        Tabela.setModel(modelo);
        Tabela.getColumnModel().getColumn(0).setPreferredWidth(80);
        Tabela.getColumnModel().getColumn(0).setResizable(false);
        Tabela.getColumnModel().getColumn(1).setPreferredWidth(310);
        Tabela.getColumnModel().getColumn(1).setResizable(false);
        Tabela.getColumnModel().getColumn(2).setPreferredWidth(150);
        Tabela.getColumnModel().getColumn(2).setResizable(false);
        Tabela.getTableHeader().setReorderingAllowed(false);
        Tabela.setAutoResizeMode(Tabela.AUTO_RESIZE_OFF);
        Tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBairro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JComboBox<String> jComboBoxCidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JButton jbuttonAdicionar;
    private javax.swing.JButton jbuttonAlterar;
    // End of variables declaration//GEN-END:variables

    private void inserirCidade() {
        try {
            String nomeCidade = jTextFieldNome.getText();

            if (nomeCidade == null || nomeCidade.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nome Do bairro está vazio");
                return;
            }
            ControleBairro control = new ControleBairro();
            modBairro.setNome(jTextFieldNome.getText());
            connCidade.executaSQL("select * from TB_cidade where nome_cidade='" + jComboBoxCidade.getSelectedItem() + "'");
            connCidade.rs.first();
            int idCidade = connCidade.rs.getInt("id_cidade");
            modBairro.setCodCidade(idCidade);
            control.InserirBairro(modBairro);
            preecherTabela(" select * from tb_bairro inner join tb_cidade on tb_bairro.id_cidade = tb_cidade.id_cidade");
            jTextFieldNome.setEnabled(false);
            jbuttonAlterar.setEnabled(false);
            jButtonDelete.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jbuttonAdicionar.setEnabled(true);
            jTextFieldNome.setText("");
            jTextFieldCod.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "erro ao Salvar!/n ERRO:" + ex);
        }

    }
}
